In [1]:
import numpy as np

a = np.array([3,4,5,6])
print(a)

[3 4 5 6]


In [6]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000* (toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("For loop: " + str(1000* (toc-tic)) + "ms")

250345.0333872837
Vectorized version: 3.384828567504883ms
250345.03338726927
For loop: 2446.2342262268066ms


In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 0.11084125  1.66741287  0.18432266 -0.69560711 -0.64720908]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.11084125  1.66741287  0.18432266 -0.69560711 -0.64720908]


In [5]:
print(np.dot(a, a.T))

3.729275156320763


In [6]:
a = np.random.randn(5, 1)
print(a)

[[-1.22104328]
 [-0.79506256]
 [ 0.23341444]
 [ 0.18198296]
 [ 0.48916949]]


In [7]:
print(a.T)

[[-1.22104328 -0.79506256  0.23341444  0.18198296  0.48916949]]


In [10]:
print(np.dot(a, a.T))

[[ 1.49094668  0.97080579 -0.28500913 -0.22220907 -0.59729712]
 [ 0.97080579  0.63212447 -0.18557908 -0.14468784 -0.38892035]
 [-0.28500913 -0.18557908  0.0544823   0.04247745  0.11417922]
 [-0.22220907 -0.14468784  0.04247745  0.0331178   0.08902051]
 [-0.59729712 -0.38892035  0.11417922  0.08902051  0.23928679]]
